app:
  auth-server: localhost

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.server.port: 4004
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.metrics.tags.application: ${spring.application.name}

---
spring.profiles: docker

spring.cloud.stream.kafka.binder.brokers: kafkak

spring.zipkin.sender.type: kafka
spring.sleuth.sampler.probability: 1.0
spring.kafka.bootstrap-servers: kafkak:9092

app:
  auth-server: auth-server
