global:
  scrape_interval:   15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'product-monitoring'

scrape_configs:
- job_name:       'product-job'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['product.hands-on:4004']
    labels:
      application: 'product'
- job_name:       'product-composite-job'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['product-composite.hands-on:4004']
    labels:
      application: 'product-composite'
- job_name:       'recommendation-job'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['recommendation.hands-on:4004']
    labels:
      application: 'recommendation'
- job_name:       'review-job'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['review.hands-on:4004']
    labels:
      application: 'review'
