
security:
  basic:
    enabled: false

management.health.circuitbreakers.enabled: true

api:
  common:
    version:
    title:
    description:
    termsOfServiceUrl:
    license:
    licenseUrl:

    contact:
      name:
      url:
      email: