apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.0.0
        env:
          - name:  GF_SECURITY_ADMIN_PASSWORD
            value: "password"
          - name:  GF_USERS_ALLOW_SIGN_UP
            value: "false"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: datasource
          mountPath: /etc/grafana/provisioning/
        - name: datasource
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: datasource
        configMap:
          name: "datasource"

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    service: grafana
spec:
  type: NodePort
  selector:
    run: grafana
  ports:
  - port: 3000
    targetPort: 3000
