server.port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/pradeepmani/escape/handsonWk/config-repo

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker

spring.cloud.config.server.native.searchLocations: file:///config-repo

